//! FFI bindings for TinySoundFont (tsf) C library.
//!
//! These bindings are generated manually from the TinySoundFont v0.9 header.
//! The `tsf` struct is opaque — all interaction is through the C API functions.
//!
//! Reference: https://github.com/schellingb/TinySoundFont

/* automatically generated by rust-bindgen */

use std::os::raw::*;

/// Opaque TinySoundFont synthesizer handle.
///
/// Created by `tsf_load_memory` or `tsf_load_filename`, freed by `tsf_close`.
/// All tsf_* functions take a `*mut tsf` as their first parameter.
#[repr(C)]
pub struct tsf {
    _private: [u8; 0],
}

/// Output mode for tsf_render_* functions.
#[repr(C)]
#[allow(non_camel_case_types)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum TSFOutputMode {
    /// Two channels with single left/right samples one after another
    TSF_STEREO_INTERLEAVED = 0,
    /// Two channels with all samples for the left channel first then right
    TSF_STEREO_UNWEAVED = 1,
    /// A single channel (stereo instruments are mixed into center)
    TSF_MONO = 2,
}

/// Stream structure for the generic loading.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tsf_stream {
    /// Custom data given to the functions as the first parameter
    pub data: *mut c_void,
    /// Function pointer: read 'size' bytes into ptr (returns number of read bytes)
    pub read:
        Option<unsafe extern "C" fn(data: *mut c_void, ptr: *mut c_void, size: c_uint) -> c_int>,
    /// Function pointer: skip ahead over 'count' bytes (returns 1 on success, 0 on error)
    pub skip: Option<unsafe extern "C" fn(data: *mut c_void, count: c_uint) -> c_int>,
}

unsafe extern "C" {
    // =========================================================================
    // Loading
    // =========================================================================

    /// Load a SoundFont from a block of memory.
    /// Returns null pointer on failure.
    pub fn tsf_load_memory(buffer: *const c_void, size: c_int) -> *mut tsf;

    /// Directly load a SoundFont from a .sf2 file path.
    /// Returns null pointer on failure.
    pub fn tsf_load_filename(filename: *const c_char) -> *mut tsf;

    /// Generic SoundFont loading using a stream structure.
    /// Returns null pointer on failure.
    pub fn tsf_load(stream: *mut tsf_stream) -> *mut tsf;

    /// Copy a tsf instance. The copy shares the underlying soundfont data.
    /// Use `tsf_close` to free it.
    pub fn tsf_copy(f: *mut tsf) -> *mut tsf;

    // =========================================================================
    // Lifecycle
    // =========================================================================

    /// Free the memory related to this tsf instance.
    pub fn tsf_close(f: *mut tsf);

    /// Stop all playing notes immediately and reset all channel parameters.
    pub fn tsf_reset(f: *mut tsf);

    // =========================================================================
    // Preset queries
    // =========================================================================

    /// Returns the preset index from a bank and preset number, or -1 if not found.
    pub fn tsf_get_presetindex(f: *const tsf, bank: c_int, preset_number: c_int) -> c_int;

    /// Returns the number of presets in the loaded SoundFont.
    pub fn tsf_get_presetcount(f: *const tsf) -> c_int;

    /// Returns the name of a preset by index (>= 0 and < tsf_get_presetcount()).
    pub fn tsf_get_presetname(f: *const tsf, preset_index: c_int) -> *const c_char;

    /// Returns the name of a preset by bank and preset number.
    pub fn tsf_bank_get_presetname(
        f: *const tsf,
        bank: c_int,
        preset_number: c_int,
    ) -> *const c_char;

    // =========================================================================
    // Output configuration
    // =========================================================================

    /// Setup the parameters for the voice render methods.
    ///
    /// - `outputmode`: mono or stereo channel ordering (TSF_STEREO_INTERLEAVED, etc.)
    /// - `samplerate`: samples per second (output frequency)
    /// - `global_gain_db`: volume gain in decibels (>0 means higher, <0 means lower)
    pub fn tsf_set_output(
        f: *mut tsf,
        outputmode: TSFOutputMode,
        samplerate: c_int,
        global_gain_db: c_float,
    );

    /// Set the global gain as a volume factor (1.0 = 100%).
    pub fn tsf_set_volume(f: *mut tsf, global_gain: c_float);

    /// Set the maximum number of voices to play simultaneously.
    /// Returns 0 if allocation failed, otherwise 1.
    pub fn tsf_set_max_voices(f: *mut tsf, max_voices: c_int) -> c_int;

    // =========================================================================
    // Preset-based note on/off
    // =========================================================================

    /// Start playing a note using a preset index.
    /// Returns 0 if voice allocation failed, otherwise 1.
    pub fn tsf_note_on(f: *mut tsf, preset_index: c_int, key: c_int, vel: c_float) -> c_int;

    /// Stop playing a note on a preset.
    pub fn tsf_note_off(f: *mut tsf, preset_index: c_int, key: c_int);

    /// Stop playing all notes (with sustain and release).
    pub fn tsf_note_off_all(f: *mut tsf);

    /// Returns the number of active voices.
    pub fn tsf_active_voice_count(f: *mut tsf) -> c_int;

    // =========================================================================
    // Bank-based note on/off
    // =========================================================================

    /// Start playing a note using bank/preset number.
    /// Returns 0 if preset does not exist or allocation failed, otherwise 1.
    pub fn tsf_bank_note_on(
        f: *mut tsf,
        bank: c_int,
        preset_number: c_int,
        key: c_int,
        vel: c_float,
    ) -> c_int;

    /// Stop playing a note using bank/preset number.
    /// Returns 0 if preset does not exist, otherwise 1.
    pub fn tsf_bank_note_off(f: *mut tsf, bank: c_int, preset_number: c_int, key: c_int) -> c_int;

    // =========================================================================
    // Rendering
    // =========================================================================

    /// Render output as signed 16-bit values.
    /// `samples`: number of samples to render.
    /// `flag_mixing`: if 0 clear the buffer first, otherwise mix into existing data.
    pub fn tsf_render_short(f: *mut tsf, buffer: *mut c_short, samples: c_int, flag_mixing: c_int);

    /// Render output as 32-bit float values.
    /// `samples`: number of samples to render.
    /// `flag_mixing`: if 0 clear the buffer first, otherwise mix into existing data.
    pub fn tsf_render_float(f: *mut tsf, buffer: *mut c_float, samples: c_int, flag_mixing: c_int);

    // =========================================================================
    // Channel-based preset selection
    // =========================================================================

    /// Set channel preset by index.
    pub fn tsf_channel_set_presetindex(f: *mut tsf, channel: c_int, preset_index: c_int) -> c_int;

    /// Set channel preset by preset number.
    /// `flag_mididrums`: 0 for normal, otherwise apply MIDI drum channel rules.
    pub fn tsf_channel_set_presetnumber(
        f: *mut tsf,
        channel: c_int,
        preset_number: c_int,
        flag_mididrums: c_int,
    ) -> c_int;

    /// Set channel bank.
    pub fn tsf_channel_set_bank(f: *mut tsf, channel: c_int, bank: c_int) -> c_int;

    /// Set channel bank and preset together.
    pub fn tsf_channel_set_bank_preset(
        f: *mut tsf,
        channel: c_int,
        bank: c_int,
        preset_number: c_int,
    ) -> c_int;

    // =========================================================================
    // Channel parameters
    // =========================================================================

    /// Set stereo panning (0.0 = left, 0.5 = center, 1.0 = right).
    pub fn tsf_channel_set_pan(f: *mut tsf, channel: c_int, pan: c_float) -> c_int;

    /// Set linear volume scale factor (1.0 = full).
    pub fn tsf_channel_set_volume(f: *mut tsf, channel: c_int, volume: c_float) -> c_int;

    /// Set pitch wheel position (0 to 16383, default 8192).
    pub fn tsf_channel_set_pitchwheel(f: *mut tsf, channel: c_int, pitch_wheel: c_int) -> c_int;

    /// Set pitch wheel range in semitones (default 2.0).
    pub fn tsf_channel_set_pitchrange(f: *mut tsf, channel: c_int, pitch_range: c_float) -> c_int;

    /// Set tuning in semitones (default 0.0).
    pub fn tsf_channel_set_tuning(f: *mut tsf, channel: c_int, tuning: c_float) -> c_int;

    /// Set sustain pedal (0 = release held notes and disable, 1 = enable).
    pub fn tsf_channel_set_sustain(f: *mut tsf, channel: c_int, flag_sustain: c_int) -> c_int;

    // =========================================================================
    // Channel-based note on/off
    // =========================================================================

    /// Start playing a note on a channel (channel preset must be set first).
    /// Returns 0 on voice allocation failure, otherwise 1.
    pub fn tsf_channel_note_on(f: *mut tsf, channel: c_int, key: c_int, vel: c_float) -> c_int;

    /// Stop playing a note on a channel (with sustain and release).
    pub fn tsf_channel_note_off(f: *mut tsf, channel: c_int, key: c_int);

    /// Stop playing all notes on a channel (with sustain and release).
    pub fn tsf_channel_note_off_all(f: *mut tsf, channel: c_int);

    /// Stop all sounds on a channel immediately (no release).
    pub fn tsf_channel_sounds_off_all(f: *mut tsf, channel: c_int);

    // =========================================================================
    // Channel MIDI control
    // =========================================================================

    /// Apply a MIDI control change to the channel.
    /// Returns 0 on channel allocation failure, otherwise 1.
    pub fn tsf_channel_midi_control(
        f: *mut tsf,
        channel: c_int,
        controller: c_int,
        control_value: c_int,
    ) -> c_int;

    // =========================================================================
    // Channel getters
    // =========================================================================

    pub fn tsf_channel_get_preset_index(f: *mut tsf, channel: c_int) -> c_int;
    pub fn tsf_channel_get_preset_bank(f: *mut tsf, channel: c_int) -> c_int;
    pub fn tsf_channel_get_preset_number(f: *mut tsf, channel: c_int) -> c_int;
    pub fn tsf_channel_get_pan(f: *mut tsf, channel: c_int) -> c_float;
    pub fn tsf_channel_get_volume(f: *mut tsf, channel: c_int) -> c_float;
    pub fn tsf_channel_get_pitchwheel(f: *mut tsf, channel: c_int) -> c_int;
    pub fn tsf_channel_get_pitchrange(f: *mut tsf, channel: c_int) -> c_float;
    pub fn tsf_channel_get_tuning(f: *mut tsf, channel: c_int) -> c_float;
}
